# Generated by Django 3.2.3 on 2021-08-12 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, max_length=500, null=True)),
                ('task_customer', models.CharField(blank=True, max_length=500, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=500, null=True)),
                ('task_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('modus', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('suspect', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('days_counter', models.CharField(blank=True, max_length=500, null=True)),
                ('task_days', models.CharField(blank=True, max_length=500, null=True)),
                ('exceed_days', models.CharField(blank=True, max_length=500, null=True)),
                ('task_deadline', models.DateTimeField(null=True)),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('posted_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
