# Generated by Django 3.2.3 on 2021-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='cis/report/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='cis/report/'),
        ),
    ]
