# Generated by Django 3.2.3 on 2021-08-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0002_auto_20210812_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
