# Generated by Django 3.2.3 on 2021-08-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurancefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(blank=True, max_length=500, null=True)),
                ('insurer', models.CharField(blank=True, max_length=500, null=True)),
                ('claimant', models.CharField(blank=True, max_length=500, null=True)),
                ('driver', models.CharField(blank=True, max_length=500, null=True)),
                ('deceased', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
