# Generated by Django 3.2.3 on 2021-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancefile',
            name='insurance_found',
            field=models.CharField(default='Your Search is Found In Insurance Database', max_length=255),
        ),
    ]
