# Generated by Django 3.2.3 on 2021-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rusumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.CharField(blank=True, max_length=100, null=True)),
                ('f', models.CharField(blank=True, max_length=100, null=True)),
                ('g', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
