# Generated by Django 3.2.3 on 2021-08-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kye', '0002_rusumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('tel', models.CharField(blank=True, max_length=500, null=True)),
                ('fax', models.CharField(blank=True, max_length=500, null=True)),
                ('order_number', models.CharField(blank=True, max_length=500, null=True)),
                ('show_avarage', models.CharField(blank=True, max_length=500, null=True)),
                ('show_general', models.CharField(blank=True, max_length=500, null=True)),
                ('display_package', models.CharField(blank=True, max_length=500, null=True)),
                ('allow_excel', models.CharField(blank=True, max_length=500, null=True)),
                ('allow_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('days_to_basic', models.CharField(blank=True, max_length=500, null=True)),
                ('days_to_extended', models.CharField(blank=True, max_length=500, null=True)),
                ('display_biometric', models.CharField(blank=True, max_length=500, null=True)),
                ('show_statistics', models.CharField(blank=True, max_length=500, null=True)),
                ('allow_import', models.CharField(blank=True, max_length=500, null=True)),
                ('idcheck', models.CharField(blank=True, max_length=500, null=True)),
                ('emphistory', models.CharField(blank=True, max_length=500, null=True)),
                ('gapanalysis', models.CharField(blank=True, max_length=500, null=True)),
                ('academic', models.CharField(blank=True, max_length=500, null=True)),
                ('professional', models.CharField(blank=True, max_length=500, null=True)),
                ('cvanalysis', models.CharField(blank=True, max_length=500, null=True)),
                ('criminal', models.CharField(blank=True, max_length=500, null=True)),
                ('adverse', models.CharField(blank=True, max_length=500, null=True)),
                ('complaince', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(blank=True, max_length=100, null=True)),
                ('q', models.CharField(blank=True, max_length=100, null=True)),
                ('r', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_found', models.CharField(default='Your Search is Found In KYE Database', max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=500, null=True)),
                ('middlename', models.CharField(blank=True, max_length=500, null=True)),
                ('lastname', models.CharField(blank=True, max_length=500, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('motech', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kye.company')),
            ],
        ),
    ]
