# Generated by Django 3.2.3 on 2021-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_found',
            field=models.CharField(default='Your Search is Found In Archiving Database', max_length=255),
        ),
        migrations.AddField(
            model_name='letter',
            name='iletter_found',
            field=models.CharField(default='Your Search is Found In Incoming Letters', max_length=255),
        ),
        migrations.AddField(
            model_name='letters',
            name='oletter_found',
            field=models.CharField(default='Your Search is Found In Outgoing Letters', max_length=255),
        ),
    ]
