# Generated by Django 3.2.5 on 2021-10-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to='report/')),
                ('entity', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='entity',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
