# Generated by Django 3.2.5 on 2021-10-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_auto_20211005_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='myfile',
            field=models.FileField(upload_to=''),
        ),
    ]
